### ISSUE TITLE
config = Config("default_config.yml")  where is it ?

### ISSUE THREAD

**Issue by wentixiaogege** [SkierProjects/MultiLabelImageClassificationPytorch#2]
config = Config("default_config.yml")  where is it ?

**Comment by bitchaser12** [comment]
This is a file you will have to define yourself that includes your default configuration (that will get overriden by any other yml files like train_many_models.yml for example. I've just pushed a default_config-example.yml you can use as an example to see how this file can look like. I'll update documentation with these details when I get a chance.
